import Field from "./Field.js";
import { DATABASE } from "../../../config/constants.js";

export default class AutoNumber extends Field {
	static typeName = "AutoNumber";
	type = "number";
	adapter;
	name;

	versions = {
		[DATABASE.MySQL]: "BIGINT",
		[DATABASE.PostgreSQL]: "BIGSERIAL",
		[DATABASE.SQLServer]: "BIGINT",
		[DATABASE.Oracle]: "NUMBER",
	};

	autoIncrement = {
		[DATABASE.MySQL]: " AUTO_INCREMENT",
		[DATABASE.PostgreSQL]: "",
		[DATABASE.SQLServer]: " IDENTITY(1,1)",
		[DATABASE.Oracle]: " GENERATED BY DEFAULT AS IDENTITY",
	};

	constructor(adapter, name) {
		super();
		this.adapter = adapter;
		this.name = name;
	}

	toDefinitionQuery() {
		return this.name + " " + this.versions[this.adapter] + this.configure();
	}

	toDefinitionQueryForRename() {
		return this.versions[this.adapter];
	}

	configure() {
		if (this.adapter === DATABASE.PostgreSQL) return "";
		return this.autoIncrement[this.adapter];
	}
}
