apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: cluster-redis-pvc
   labels:
      app: cluster-redis
spec:
   accessModes:
      - ReadWriteOnce
   resources:
      requests:
         storage: 1Gi