apiVersion: v1
kind: Secret
metadata:
   name: cluster-secrets
type: Opaque
data:
   clusterId: Y2xzX0M5RzZHWDNJQ0xFUg==
   clusterAcessToken: YXRfaFlacWFoYVEyMFA1a1N2cEVKM2t5MG9wVDh6Slg1WTFWRkla
   masterToken: bXQtaFlacWFoYVEyMFA1a1N2cEVKM2t5MG9wVDh6Slg1WTFWRkla #used to access platform-core through rest api
   accessToken: YXQtMkY1Rk9Ja09YRU9tUGZ5d1dKNkpSWlhDbnpGZ3RxVklIQUo3  #used to access engine resources (monitor, scheduler, realtime, worker)
   uiBaseURL: aHR0cDovL2FwaS5kZXZlbG9wbWVudC50ZXN0 #http://api.development.test
   clusterDBURI: bW9uZ29kYitzcnY6Ly9jbHVzdGVyMC1xeGFseS5tb25nb2RiLm5ldC9hZ25vc3RfZW50ZXJwcmlzZT9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHk=
   clusterDBUser: dW1pdF9jYWttYWs=
   clusterDBPwd: RzNvVWlGaGNLY3pRSTZsSg==
   queueURL: YW1xcHM6Ly9rdm51bGJkZjpiNlJTbGtYLUNLRURmZUlPMkVtSlhvbUZBTWNVUmRyckBoaWxhcmlvdXMtbGltZS1mb3gucm1xNC5jbG91ZGFtcXAuY29tL2t2bnVsYmRmP2ZyYW1lTWF4PTAmaGVhcnRiZWF0PTYw
   cacheHostname: Y2x1c3Rlci1yZWRpcy1jbHVzdGVyaXAtc2VydmljZQ==
   cacheReadReplicaHostname: Y2x1c3Rlci1yZWRpcy1jbHVzdGVyaXAtc2VydmljZQ==
   realtimeCacheHostname: Y2x1c3Rlci1yZWRpcy1jbHVzdGVyaXAtc2VydmljZQ==
   cachePwd: bnVsbA==
   cacheReadReplicaPwd: bnVsbA==
   realtimeCachePwd: bnVsbA==
   emailServerUser: QWx0b2dpYw==
   emailServerPwd: aVMtcE5IbUJKSVhJcGpPVVhnWW1aUQ==
   passPhrase: ZDFhYjNlNGQtNGNmZC00MDJiLTg3NTUtZmEyMjVkOThiYTQw
