apiVersion: apps/v1
kind: Deployment
metadata:
   name: engine-worker-deployment
   labels:
      app: engine-worker
spec:
   replicas: 1
   selector:
      matchLabels:
         app: engine-worker
   template:
      metadata:
         labels:
            app: engine-worker
      spec:
         containers:
            - name: engine-worker
              image: agnost-enterprise/engine-worker
              # We will be using the minikube docker daemon, since the actual docker daemon on local machine are different
              # Prevent minikube docker daemon to pull images from central docker hub set imagePullPolicy to Never, so that
              # it uses the image put in minikube's docker environment, see dev.sh script how we change the docker context to minikube
              imagePullPolicy: Never
              ports:
                 - containerPort: 4000
              env:
                 - name: CACHE_PWD
                   valueFrom:
                      secretKeyRef:
                         name: cluster-secrets
                         key: cachePwd
                 - name: CACHE_READ_REPLICA_PWD
                   valueFrom:
                      secretKeyRef:
                         name: cluster-secrets
                         key: cacheReadReplicaPwd
                 - name: QUEUE_URL
                   valueFrom:
                      secretKeyRef:
                         name: cluster-secrets
                         key: queueURL
                 - name: CLUSTER_DB_URI
                   valueFrom:
                      secretKeyRef:
                         name: cluster-secrets
                         key: clusterDBURI
                 - name: CLUSTER_DB_USER
                   valueFrom:
                      secretKeyRef:
                         name: cluster-secrets
                         key: clusterDBUser
                 - name: CLUSTER_DB_PWD
                   valueFrom:
                      secretKeyRef:
                         name: cluster-secrets
                         key: clusterDBPwd
                 - name: MASTER_TOKEN
                   valueFrom:
                      secretKeyRef:
                         name: cluster-secrets
                         key: masterToken
                 - name: ACCESS_TOKEN
                   valueFrom:
                      secretKeyRef:
                         name: cluster-secrets
                         key: accessToken