
apiVersion: apps/v1
kind: Deployment
metadata:
   name: engine-realtime-deployment
   labels:
      app: engine-realtime
spec:
   replicas: 1
   selector:
      matchLabels:
         app: engine-realtime
   template:
      metadata:
         labels:
            app: engine-realtime
      spec:
         containers:
            - name: engine-realtime
              image: agnost-community/engine/realtime
              imagePullPolicy: Never
              ports:
                 - containerPort: 4000
              env:
                 - name: CACHE_HOSTNAME
                   value: redis-master       
                 - name: CACHE_PWD
                   valueFrom:
                      secretKeyRef:
                         name: redis-password
                         key: password
                 - name: REALTIME_CACHE_HOSTNAME
                   value: redis-master           
                 - name: REALTIME_CACHE_PWD
                   valueFrom:
                      secretKeyRef:
                         name: redis-password
                         key: password
                 - name: MASTER_TOKEN
                   valueFrom:
                      secretKeyRef:
                         name: cluster-secrets
                         key: masterToken
                 - name: ACCESS_TOKEN
                   valueFrom:
                      secretKeyRef:
                         name: cluster-secrets
                         key: accessToken