
apiVersion: apps/v1
kind: Deployment
metadata:
   name: engine-scheduler-deployment
   labels:
      app: engine-scheduler
spec:
   replicas: 1
   selector:
      matchLabels:
         app: engine-scheduler
   template:
      metadata:
         labels:
            app: engine-scheduler
      spec:
         containers:
            - name: engine-scheduler
              image: agnost-enterprise/engine-scheduler
              imagePullPolicy: Never
              ports:
                 - containerPort: 4000
              env:
                 - name: CACHE_HOSTNAME
                   valueFrom:
                      secretKeyRef:
                         name: cluster-secrets
                         key: cacheHostname          
                 - name: CACHE_READ_REPLICA_HOSTNAME
                   valueFrom:
                      secretKeyRef:
                         name: cluster-secrets
                         key: cacheReadReplicaHostname   
                 - name: CACHE_PWD
                   valueFrom:
                      secretKeyRef:
                         name: cluster-secrets
                         key: cachePwd
                 - name: CACHE_READ_REPLICA_PWD
                   valueFrom:
                      secretKeyRef:
                         name: cluster-secrets
                         key: cacheReadReplicaPwd
                 - name: QUEUE_USERNAME
                   valueFrom:
                      secretKeyRef:
                         name: cluster-secrets
                         key: queueUsername
                 - name: QUEUE_PASSWORD
                   valueFrom:
                      secretKeyRef:
                         name: cluster-secrets
                         key: queuePassword
                 - name: QUEUE_HOST
                   valueFrom:
                      secretKeyRef:
                         name: cluster-secrets
                         key: queueHost
                 - name: CLUSTER_DB_URI
                   valueFrom:
                      secretKeyRef:
                         name: cluster-secrets
                         key: clusterDBURI
                 - name: CLUSTER_DB_USER
                   valueFrom:
                      secretKeyRef:
                         name: cluster-secrets
                         key: clusterDBUser
                 - name: CLUSTER_DB_PWD
                   valueFrom:
                      secretKeyRef:
                         name: cluster-secrets
                         key: clusterDBPwd
                 - name: MASTER_TOKEN
                   valueFrom:
                      secretKeyRef:
                         name: cluster-secrets
                         key: masterToken
                 - name: ACCESS_TOKEN
                   valueFrom:
                      secretKeyRef:
                         name: cluster-secrets
                         key: accessToken