
apiVersion: apps/v1
kind: Deployment
metadata:
   name: engine-scheduler-deployment
   labels:
      app: engine-scheduler
spec:
   replicas: 1
   selector:
      matchLabels:
         app: engine-scheduler
   template:
      metadata:
         labels:
            app: engine-scheduler
      spec:
         containers:
            - name: engine-scheduler
              image: agnost-community/engine/scheduler
              imagePullPolicy: Never
              ports:
                 - containerPort: 4000
              env:
                 - name: CACHE_HOSTNAME
                   value: redis-master          
                 - name: CACHE_PWD
                   valueFrom:
                      secretKeyRef:
                         name: redis-password
                         key: password
                 - name: QUEUE_USERNAME
                   valueFrom:
                      secretKeyRef:
                         name: rabbitmq-default-user
                         key: username
                 - name: QUEUE_PASSWORD
                   valueFrom:
                      secretKeyRef:
                         name: rabbitmq-default-user
                         key: password
                 - name: QUEUE_HOST
                   valueFrom:
                      secretKeyRef:
                         name: rabbitmq-default-user
                         key: host
                 - name: CLUSTER_DB_URI
                   valueFrom:
                      secretKeyRef:
                         name: cluster-secrets
                         key: clusterDBURI
                 - name: CLUSTER_DB_USER
                   value: "mongo-user"
                 - name: CLUSTER_DB_PWD
                   valueFrom:
                      secretKeyRef:
                         name: mongodb-admin-password
                         key: password
                 - name: MASTER_TOKEN
                   valueFrom:
                      secretKeyRef:
                         name: cluster-secrets
                         key: masterToken
                 - name: ACCESS_TOKEN
                   valueFrom:
                      secretKeyRef:
                         name: cluster-secrets
                         key: accessToken
                 - name: NAMESPACE
                   value: yoda