apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
   name: ingress-service
   annotations:
      kubernetes.io/ingress.class: 'nginx'
      nginx.ingress.kubernetes.io/proxy-body-size: 500m
      nginx.ingress.kubernetes.io/proxy-connect-timeout: '6000'
      nginx.ingress.kubernetes.io/proxy-send-timeout: '6000'
      nginx.ingress.kubernetes.io/proxy-read-timeout: '6000'
      nginx.ingress.kubernetes.io/proxy-next-upstream-timeout: '6000'
      nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
   defaultBackend:
      service:
         name: engine-default-backend-clusterip-service
         port:
            number: 5000
   rules:
      - host: 
        http:
           paths:
              - path: /api/(.*)
                pathType: Prefix
                backend:
                   service:
                      name: platform-core-clusterip-service
                      port:
                         number: 4000
      - http:
           paths:
              - path: /realtime/(.*)
                pathType: Prefix
                backend:
                   service:
                      name: engine-realtime-clusterip-service
                      port:
                         number: 4000
      - host: 
        http:
           paths:
              - path: /sync/(.*)
                pathType: Prefix
                backend:
                   service:
                      name: platform-sync-clusterip-service
                      port:
                         number: 4000
      - host: 
        http:
           paths:
              - path: /worker/(.*)
                pathType: Prefix
                backend:
                   service:
                      name: engine-worker-clusterip-service
                      port:
                         number: 4000