apiVersion: apps/v1
kind: Deployment
metadata:
   name: platform-worker-deployment
   labels:
      app: platform-worker
spec:
   replicas: 1
   selector:
      matchLabels:
         app: platform-worker
   template:
      metadata:
         labels:
            app: platform-worker
      spec:
         containers:
            - name: platform-worker
              image: agnost-enterprise/platform-worker
              # We will be using the minikube docker daemon, since the actual docker daemon on local machine are different
              # Prevent minikube docker daemon to pull images from central docker hub set imagePullPolicy to Never, so that
              # it uses the image put in minikube's docker environment, see dev.sh script how we change the docker context to minikube
              imagePullPolicy: Never
              env:
                 - name: CACHE_HOSTNAME
                   valueFrom:
                      secretKeyRef:
                         name: cluster-secrets
                         key: cacheHostname          
                 - name: CACHE_READ_REPLICA_HOSTNAME
                   valueFrom:
                      secretKeyRef:
                         name: cluster-secrets
                         key: cacheReadReplicaHostname   
                 - name: CACHE_PWD
                   valueFrom:
                      secretKeyRef:
                         name: cluster-secrets
                         key: cachePwd
                 - name: CACHE_READ_REPLICA_PWD
                   valueFrom:
                      secretKeyRef:
                         name: cluster-secrets
                         key: cacheReadReplicaPwd
                 - name: QUEUE_USERNAME
                   valueFrom:
                      secretKeyRef:
                         name: cluster-secrets
                         key: queueUsername
                 - name: QUEUE_PASSWORD
                   valueFrom:
                      secretKeyRef:
                         name: cluster-secrets
                         key: queuePassword
                 - name: QUEUE_HOST
                   valueFrom:
                      secretKeyRef:
                         name: cluster-secrets
                         key: queueHost
                 - name: EMAIL_SERVER_HOST
                   valueFrom:
                      secretKeyRef:
                         name: cluster-secrets
                         key: emailServerHost
                 - name: EMAIL_SERVER_PORT
                   valueFrom:
                      secretKeyRef:
                         name: cluster-secrets
                         key: emailServerPort
                 - name: EMAIL_SERVER_SECURE
                   valueFrom:
                      secretKeyRef:
                         name: cluster-secrets
                         key: emailServerSecure
                 - name: EMAIL_SERVER_USER
                   valueFrom:
                      secretKeyRef:
                         name: cluster-secrets
                         key: emailServerUser
                 - name: EMAIL_SERVER_PWD
                   valueFrom:
                      secretKeyRef:
                         name: cluster-secrets
                         key: emailServerPwd
                 - name: CLUSTER_DB_URI
                   valueFrom:
                      secretKeyRef:
                         name: cluster-secrets
                         key: clusterDBURI
                 - name: CLUSTER_DB_USER
                   valueFrom:
                      secretKeyRef:
                         name: cluster-secrets
                         key: clusterDBUser
                 - name: CLUSTER_DB_PWD
                   valueFrom:
                      secretKeyRef:
                         name: cluster-secrets
                         key: clusterDBPwd
                 - name: MASTER_TOKEN
                   valueFrom:
                      secretKeyRef:
                         name: cluster-secrets
                         key: masterToken