apiVersion: apps/v1
kind: Deployment
metadata:
   name: platform-core-deployment
   labels:
      app: platform-core
spec:
   replicas: 1
   selector:
      matchLabels:
         app: platform-core
   template:
      metadata:
         labels:
            app: platform-core
      spec:
         volumes:
            - name: cluster-storage
              persistentVolumeClaim:
                 claimName: cluster-storage-pvc
         containers:
            - name: platform-core
              image: agnost-community/platform/core
              # We will be using the minikube docker daemon, since the actual docker daemon on local machine are different
              # Prevent minikube docker daemon to pull images from central docker hub set imagePullPolicy to Never, so that
              # it uses the image put in minikube's docker environment, see dev.sh script how we change the docker context to minikube
              imagePullPolicy: Never
              ports:
                 - containerPort: 4000
              volumeMounts:
                 - name: cluster-storage
                   mountPath: /storage
              env:
                 - name: CACHE_HOSTNAME
                   value: redis-master        
                 - name: CACHE_READ_REPLICA_HOSTNAME
                   value: redis-replicas   
                 - name: CACHE_PWD
                   valueFrom:
                      secretKeyRef:
                         name: redis-password
                         key: password
                 - name: CACHE_READ_REPLICA_PWD
                   valueFrom:
                      secretKeyRef:
                         name: redis-password
                         key: password
                 - name: QUEUE_USERNAME
                   valueFrom:
                      secretKeyRef:
                         name: rabbitmq-credentials
                         key: username
                 - name: QUEUE_PASSWORD
                   valueFrom:
                      secretKeyRef:
                         name: rabbitmq-credentials
                         key: password
                 - name: QUEUE_HOST
                   valueFrom:
                      secretKeyRef:
                         name: rabbitmq-credentials
                         key: host
                 - name: CLUSTER_DB_URI
                   valueFrom:
                      secretKeyRef:
                         name: cluster-secrets
                         key: clusterDBURI
                 - name: CLUSTER_DB_USER
                   value: "mongo-user"
                 - name: CLUSTER_DB_PWD
                   valueFrom:
                      secretKeyRef:
                         name: mongodb-admin-password
                         key: password
                 - name: PASSPHRASE
                   valueFrom:
                      secretKeyRef:
                         name: cluster-secrets
                         key: passPhrase
                 - name: CLUSTER_ACCESS_TOKEN
                   valueFrom:
                      secretKeyRef:
                         name: cluster-secrets
                         key: clusterAcessToken
                 - name: MASTER_TOKEN
                   valueFrom:
                      secretKeyRef:
                         name: cluster-secrets
                         key: masterToken
                 - name: ACCESS_TOKEN
                   valueFrom:
                      secretKeyRef:
                         name: cluster-secrets
                         key: accessToken
