apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"env-ycdptagssz9v","skaffold.dev/run-id":"9ec7d2f9-6c36-4072-a06f-c9889c0e45aa"},"name":"env-ycdptagssz9v-deployment","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"env-ycdptagssz9v"}},"template":{"metadata":{"labels":{"app":"env-ycdptagssz9v","skaffold.dev/run-id":"9ec7d2f9-6c36-4072-a06f-c9889c0e45aa"}},"spec":{"containers":[{"env":[{"name":"CACHE_HOSTNAME","value":"redis-master"},{"name":"CACHE_READ_REPLICA_HOSTNAME","value":"redis-replicas"},{"name":"CACHE_PWD","valueFrom":{"secretKeyRef":{"key":"password","name":"redis-password"}}},{"name":"CACHE_READ_REPLICA_PWD","valueFrom":{"secretKeyRef":{"key":"password","name":"redis-password"}}},{"name":"QUEUE_USERNAME","valueFrom":{"secretKeyRef":{"key":"username","name":"rabbitmq-credentials"}}},{"name":"QUEUE_PASSWORD","valueFrom":{"secretKeyRef":{"key":"password","name":"rabbitmq-credentials"}}},{"name":"QUEUE_HOST","valueFrom":{"secretKeyRef":{"key":"host","name":"rabbitmq-credentials"}}},{"name":"CLUSTER_DB_URI","valueFrom":{"secretKeyRef":{"key":"clusterDBURI","name":"cluster-secrets"}}},{"name":"CLUSTER_DB_USER","value":"mongo-user"},{"name":"CLUSTER_DB_PWD","valueFrom":{"secretKeyRef":{"key":"password","name":"mongodb-admin-password"}}},{"name":"MASTER_TOKEN","valueFrom":{"secretKeyRef":{"key":"masterToken","name":"cluster-secrets"}}},{"name":"POD_NAME","valueFrom":{"fieldRef":{"fieldPath":"metadata.name"}}},{"name":"PASSPHRASE","valueFrom":{"secretKeyRef":{"key":"passPhrase","name":"cluster-secrets"}}},{"name":"AGNOST_ENVIRONMENT_ID","value":"env-ycdptagssz9v"},{"name":"AGNOST_ENGINE_ID","value":"env-ycdptagssz9v"}],"image":"agnost-community/engine/core:2c52f1cb49d8d57133ec247227a296a13714f7cb9fa3b2051d44ca470f9809e3","imagePullPolicy":"Never","name":"env-ycdptagssz9v","ports":[{"containerPort":4000}]}]}}}}
  creationTimestamp: "2023-06-15T19:57:41Z"
  generation: 1
  labels:
    app: env-ycdptagssz9v
    skaffold.dev/run-id: 9ec7d2f9-6c36-4072-a06f-c9889c0e45aa
  name: env-ycdptagssz9v-deployment
  namespace: default
  resourceVersion: "606182"
  uid: 2759e975-2d2b-4066-aeed-d2a0d22321d8
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: env-ycdptagssz9v
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: env-ycdptagssz9v
        skaffold.dev/run-id: 9ec7d2f9-6c36-4072-a06f-c9889c0e45aa
    spec:
      containers:
      - env:
        - name: CACHE_HOSTNAME
          value: redis-master
        - name: CACHE_READ_REPLICA_HOSTNAME
          value: redis-replicas
        - name: CACHE_PWD
          valueFrom:
            secretKeyRef:
              key: password
              name: redis-password
        - name: CACHE_READ_REPLICA_PWD
          valueFrom:
            secretKeyRef:
              key: password
              name: redis-password
        - name: QUEUE_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: rabbitmq-credentials
        - name: QUEUE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: rabbitmq-credentials
        - name: QUEUE_HOST
          valueFrom:
            secretKeyRef:
              key: host
              name: rabbitmq-credentials
        - name: CLUSTER_DB_URI
          valueFrom:
            secretKeyRef:
              key: clusterDBURI
              name: cluster-secrets
        - name: CLUSTER_DB_USER
          value: mongo-user
        - name: CLUSTER_DB_PWD
          valueFrom:
            secretKeyRef:
              key: password
              name: mongodb-admin-password
        - name: MASTER_TOKEN
          valueFrom:
            secretKeyRef:
              key: masterToken
              name: cluster-secrets
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: PASSPHRASE
          valueFrom:
            secretKeyRef:
              key: passPhrase
              name: cluster-secrets
        - name: AGNOST_ENVIRONMENT_ID
          value: env-ycdptagssz9v
        - name: AGNOST_ENGINE_ID
          value: env-ycdptagssz9v
        image: agnost-community/engine/core:2c52f1cb49d8d57133ec247227a296a13714f7cb9fa3b2051d44ca470f9809e3
        imagePullPolicy: Never
        name: env-ycdptagssz9v
        ports:
        - containerPort: 4000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-06-15T19:57:50Z"
    lastUpdateTime: "2023-06-15T19:57:50Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-06-15T19:57:41Z"
    lastUpdateTime: "2023-06-15T19:57:50Z"
    message: ReplicaSet "env-ycdptagssz9v-deployment-6c94799bb" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
