const ERROR_CODES = {
	// Platform specific error codes
	internalServerError: "internal_server_error",
	rateLimitExceeded: "rate_limit_exceeded",
	resourceNotFound: "resource_not_found",
	invalidRequestBody: "invalid_request_body",
	invalidContentType: "invalid_content_type",
	validationError: "validation_error",
	invalidValidationCode: "invalid_validation_code",
	invalidCredentials: "invalid_credentials",
	pendingAccount: "pending_account",
	pendingEmailConfirmation: "pending_email_confirmation",
	missingAccessToken: "missing_access_token",
	missingRefreshToken: "missing_refresh_token",
	invalidSession: "invalid_session",
	invalidAccessToken: "invalid_access_token",
	invalidRefreshToken: "invalid_refresh_token",
	noOAuthProvider: "no_oauth_provider",
	noOAuthProviderConfig: "no_oauth_provider_config",
	permissionDenied: "permission_denied",
	DBError: "database_error",
	invalidIdentifier: "invalid_identifier",
	invalidUser: "invalid_user",
	notAllowed: "not_allowed",
	invalidToken: "invalid_token",
	fileUploadError: "file_upload_error",
	unauthorized: "unauthorized",
	notFound: "not_found",
	setupCompleted: "setup_completed",
	connectionError: "connection_error",
	invalidUserDataModel: "invalid_user_data_model",
	invalidTimeRange: "invalid_time_range",
	invalidBucketSize: "invalid_bucket_size",
	fileSizeTooLarge: "file_size_too_large",
	fileUploadError: "file_upload_error",
	badRequest: "bad_request",
};
export default ERROR_CODES;
