apiVersion: batch/v1
kind: CronJob
metadata:
  name: db-backup
spec:
  schedule: "1 3 * * *"  # This is UTC time
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: db-backup
            image: gcr.io/agnost-community/db-backup-tooling:v0.1.3
            env: []
            command: ["/bin/bash"]
            args: ["-c", "/scripts/backup.sh -t ${DB_TYPE} -b ${BUCKET_TYPE} -n ${BUCKET_NAME}"]
            volumeMounts: []
          restartPolicy: OnFailure
          volumes: []
