apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
type: Opaque
stringData:
  username: mquser
  password: mypassword
  host: service-name
---
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
spec:
  image: docker.io/bitnami/rabbitmq:3.10.2
  replicas: 3
  resources:
    requests:
      cpu: 200m
      memory: 500Mi
    limits:
      cpu: 200m
      memory: 500Mi
  persistence:
    storage: 3Gi
  override:
    statefulSet:
      spec:
        template:
          spec:
            containers:
              - name: rabbitmq
                volumeMounts:
                  - mountPath: /opt/rabbitmq/community-plugins
                    name: community-plugins
            volumes:
              - name: community-plugins
                emptyDir: {}
            initContainers:
              - command:
                  - sh
                  - -c
                  - if [[ $RMQ_VERSION =~ 3.12* ]]; then DIR="v${RMQ_VERSION}"; else DIR=${RMQ_VERSION}; fi && curl -L -v https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/${DIR}/rabbitmq_delayed_message_exchange-${RMQ_VERSION}.ez --output /community-plugins/rabbitmq_delayed_message_exchange-${RMQ_VERSION}.ez
                image: curlimages/curl
                imagePullPolicy: IfNotPresent
                name: copy-community-plugins
                env:
                  - name: RMQ_VERSION
                    value: "3.10.2"
                resources:
                  limits:
                    cpu: 100m
                    memory: 500Mi
                  requests:
                    cpu: 100m
                    memory: 500Mi
                terminationMessagePolicy: FallbackToLogsOnError
                volumeMounts:
                  - mountPath: /community-plugins/
                    name: community-plugins
  rabbitmq:
    additionalConfig: |
      default_user_tags.administrator = true
    additionalPlugins:
    - rabbitmq_delayed_message_exchange
    envConfig: |
      RABBITMQ_PLUGINS_DIR=/opt/rabbitmq/plugins:/opt/rabbitmq/community-plugins:/opt/bitnami/rabbitmq/plugins
---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: mquser
spec:
  rabbitmqClusterReference:
    name: rabbitmq
  tags:
    - administrator
  importCredentialsSecret:
    name: rabbitmq-credentials
---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: mquser-permission
spec:
  vhost: "/"
  userReference:
    name: "mquser"
  permissions:
    write: ".*"
    configure: ".*"
    read: ".*"
  rabbitmqClusterReference:
    name: rabbitmq