apiVersion: v1
data:
  accessToken: YXQtejI1YmFsdjN5dzRoYW16eW9nbmxtbWRtbXlv
  clusterAccessToken: YXQtYmp1cWVremFld2dqcmtoZXZtZ3hidXR3dHc4
  clusterDBURI: bW9uZ29kYjovL21vbmdvZGItc3ZjLmRlZmF1bHQuc3ZjL2Fnbm9zdD9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHk=
  clusterId: Y2xzLXpka3R2eW93ZDE=
  jwtSecret: dnh2endsanFxbGR0dW1kMnR1OWViMGY2bXow
  masterToken: bXQtZGpjbnp2ajNlZWIzYnl2aHQwOXR5d3IxbWNx
  passPhrase: czJpcXIwaGRydzhvYzF6bHZkZGV5dnJqbWNt
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: agnost
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2024-01-24T07:41:06Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: cluster-secrets
  namespace: default
  resourceVersion: "1170"
  uid: a90bc0ab-bf0f-4f4c-bfae-6b6b189102c4
type: Opaque