# On command line use the below command, if --trigger=polling is not added then file sync does not work
# skaffold dev --trigger='polling' --no-prune=false --cache-artifacts=false
apiVersion: skaffold/v2beta14
kind: Config
build:
   artifacts:
      - image:  agnost-community/platform/core
        context: ../platform/core
        sync:
           infer:
              - '**/*.js'
              - '**/*.json'
        docker:
           dockerfile: Dockerfile.dev
      - image: agnost-community/platform/worker
        context: ../platform/worker
        sync:
           infer:
              - '../../../agnost-server/dist/**/*.js'
              - '**/*.json'
              - '**/*.pug'
        docker:
           dockerfile: Dockerfile.dev
      - image: agnost-community/platform/sync
        context: ../platform/sync
        sync:
           infer:
              - '**/*.js'
              - '**/*.json'
              - '**/*.pug'
        docker:
           dockerfile: Dockerfile.dev
      - image: agnost-community/engine/core
        context: ../engine/core
        sync:
           infer:
              - '**/*.js'
              - '**/*.cjs'
              - '**/*.json'
        docker:
           dockerfile: Dockerfile.dev
      - image: agnost-community/engine/worker
        context: ../engine/worker
        sync:
          infer:
              - '**/*.js'
              - '**/*.json'
        docker:
          dockerfile: Dockerfile.dev
      - image: agnost-community/engine/monitor
        context: ../engine/monitor
        sync:
          infer:
              - '**/*.js'
              - '**/*.json'
        docker:
          dockerfile: Dockerfile.dev
      - image: agnost-community/engine/realtime
        context: ../engine/realtime
        sync:
          infer:
              - '**/*.js'
              - '**/*.json'
        docker:
          dockerfile: Dockerfile.dev
      - image: agnost-community/engine/scheduler
        context: ../engine/scheduler
        sync:
          infer:
              - '**/*.js'
              - '**/*.json'
        docker:
          dockerfile: Dockerfile.dev
      - image: agnost-community/studio
        context: ../studio
        sync:
           infer:
              - '**/*.js'
              - '**/*.ts'
              - '**/*.tsx'
              - '**/*.json'
              - '**/*.html'
              - '**/*.htm'
              - '**/*.css'
              - '**/*.png'
              - '**/*.jpg'
              - '**/*.svg'
              - '**/*.ico'
              - '**/*.md'
        docker:
           dockerfile: Dockerfile.dev
deploy:
   statusCheckDeadlineSeconds: 300
   kubectl:
      defaultNamespace: yoda
      manifests:
         - dev/platform-core-deployment.yaml
         - dev/platform-worker-deployment.yaml
         - dev/platform-sync-deployment.yaml
         - dev/engine-core-deployment.yaml
         - dev/engine-worker-deployment.yaml
         - dev/engine-monitor-deployment.yaml
         - dev/engine-realtime-deployment.yaml
         - dev/engine-scheduler-deployment.yaml
         - dev/studio-deployment.yaml