# On command line use the below command, if --trigger=polling is not added then file sync does not work
# skaffold dev --trigger='polling' --no-prune=false --cache-artifacts=false
apiVersion: skaffold/v2alpha3
kind: Config
build:
   artifacts:
      - image:  agnost-enterprise/platform-core
        context: ../platform/core
        sync:
           infer:
              - '**/*.js'
              - '**/*.json'
        docker:
           dockerfile: Dockerfile.dev
      - image: agnost-enterprise/platform-worker
        context: ../platform/worker
        sync:
           infer:
              - '**/*.js'
              - '**/*.json'
              - '**/*.pug'
        docker:
           dockerfile: Dockerfile.dev
      - image: agnost-enterprise/platform-sync
        context: ../platform/sync
        sync:
           infer:
              - '**/*.js'
              - '**/*.json'
              - '**/*.pug'
        docker:
           dockerfile: Dockerfile.dev
      - image: agnost-enterprise/engine-core
        context: ../engine/core
        sync:
          infer:
              - '**/*.js'
              - '**/*.json'
        docker:
          dockerfile: Dockerfile.dev
      - image: agnost-enterprise/engine-worker
        context: ../engine/worker
        sync:
          infer:
              - '**/*.js'
              - '**/*.json'
        docker:
          dockerfile: Dockerfile.dev
      - image: agnost-enterprise/engine-monitor
        context: ../engine/monitor
        sync:
          infer:
              - '**/*.js'
              - '**/*.json'
        docker:
          dockerfile: Dockerfile.dev
      - image: agnost-enterprise/engine-realtime
        context: ../engine/realtime
        sync:
          infer:
              - '**/*.js'
              - '**/*.json'
        docker:
          dockerfile: Dockerfile.dev
      - image: agnost-enterprise/engine-scheduler
        context: ../engine/scheduler
        sync:
          infer:
              - '**/*.js'
              - '**/*.json'
        docker:
          dockerfile: Dockerfile.dev
deploy:
   statusCheckDeadlineSeconds: 300
   kubectl:
      manifests:
         - dev/platform-core-deployment.yaml
         - dev/platform-worker-deployment.yaml
         - dev/platform-sync-deployment.yaml
         - dev/engine-core-deployment.yaml
         - dev/engine-worker-deployment.yaml
         - dev/engine-monitor-deployment.yaml
         - dev/engine-realtime-deployment.yaml
         - dev/engine-scheduler-deployment.yaml