apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: provisioner-role
  namespace: operators
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: provisioner-role-binding
  namespace: operators
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: provisioner-role
subjects:
- kind: ServiceAccount
  name: provisioner-sa
  namespace: default
