apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date
            resources:
              requests:
                cpu: 100m
                memory: 500Mi
              limits:
                cpu: 1000m
                memory: 1Gi
          restartPolicy: Never