export {
	SLIDER_IMAGES,
	MENU_ITEMS,
	MENU_ITEMS_FOR_PROFILE_SETTINGS,
	ORGANIZATION_MENU_ITEMS,
	APPLICATION_SETTINGS,
	ALL_NOTIFICATIONS,
	ERROR_CODES_TO_REDIRECT_LOGIN_PAGE,
} from '@/constants/constants.ts';
