name: Build on PR to Master

on:
  pull_request:
    branches: ["master"]
    paths:
      - "studio/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: |
          cd studio
          npm install

      - name: Build project
        run: |
          cd studio
          npm run build
