name: Build on PR to Master and Dev

on:
  pull_request:
    branches: ["master", "dev"]
    paths:
      - "studio/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14" # You can specify your desired Node.js version

      - name: Change directory to studio
        run: cd studio

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
