name: Provisioner

on:
  push:
    branches:
      - 'provisioner'

env:
  DOCKER_REGISTRY: 'gcr.io'
  GCR_PROJECT: 'agnost-enterprise'

jobs:
  generate_short_sha:
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ steps.short-sha.outputs.sha }}
    steps:
      -
        uses: actions/checkout@v3
      -
        uses: benjlevesque/short-sha@v2.1
        id: short-sha

  build:
    runs-on: ubuntu-latest
    needs: [generate_short_sha]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: 'Authenticate to GCP'
        id: 'auth'
        uses: google-github-actions/auth@v0
        with:
          token_format: 'access_token'
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS_ENTERPRISE }}'
      -
        name: Login to GCR
        uses: docker/login-action@v2
        with:
          registry: '${{ env.DOCKER_REGISTRY }}'
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'
      -
        name: Build and Push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          file: ./Dockerfile
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ env.GCR_PROJECT }}/provisioner:${{ needs.generate_short_sha.outputs.sha }}
            ${{ env.DOCKER_REGISTRY }}/${{ env.GCR_PROJECT }}/provisioner:latest
